# POSTTEST 7 - Modul Pengenalan TensorFlow
#### Nama : Jorghi Inzaghi Tanson
#### NIM    : 2009106069

##### Import library yang dibutuhkan

In [45]:
import tensorflow as tf

#### 1) Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor dan tampilkan isinya

In [46]:
# Deklarasi variabel random_tensor untuk membuat tensor yang berisi nilai random gunakan fungsi tf.random.normal()

random_tensor = tf.random.normal([5, 5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.5933604 , -0.35052463,  0.42444015,  0.20645753,  2.3339202 ],
       [ 0.5887018 ,  0.63107646, -2.2573323 , -1.1637964 ,  0.4790582 ],
       [-0.55197406, -0.03888295, -0.52864707,  0.2426774 ,  0.00829258],
       [-0.31521624, -0.11524713, -1.0138263 ,  0.22795753, -0.95527774],
       [-0.786682  , -1.0968654 ,  0.85248137, -1.4731542 , -0.09696788]],
      dtype=float32)>

#### 2) Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor dan tampilkan isinya

In [47]:
# Deklarasi variabel yang merupakan array yang berisi nilai prima
# Di sini saya memberi batasan berupa nilai prima di bawah 100

arrayPrima = [[2, 3, 5, 7, 11],
              [13, 17, 19, 23, 29],
              [31, 37, 41, 43, 47],
              [53, 59, 61, 67, 71],
              [73, 79, 83, 89, 97]]

# Buat variabel prime_tensor yang menampung fungsi tf.convert_to_tensor

prime_tensor = tf.convert_to_tensor(arrayPrima, dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

#### 3) Tampilkan dimensi dari kedua variable tersebut

In [48]:
# Untuk menampilkan dimensi dari 2 variabel di atas
# gunakan fungsi shape dan get_shape()

print(f'Dimensi dari variabel random_tensor: {random_tensor.shape}',
     f'Dimensi dari variabel prime_tensor: {prime_tensor.get_shape()}',
     sep='\n')

Dimensi dari variabel random_tensor: (5, 5)
Dimensi dari variabel prime_tensor: (5, 5)


#### 4) Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

##### 4.1) Operator Pangkat

In [49]:
# Gunakan fungsi tf.square() atau tf.pow() untuk melakukan operasi perpangkatan dari 2 tensor

tf.square(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[3.5207659e-01, 1.2286752e-01, 1.8014944e-01, 4.2624708e-02,
        5.4471836e+00],
       [3.4656978e-01, 3.9825749e-01, 5.0955491e+00, 1.3544221e+00,
        2.2949676e-01],
       [3.0467537e-01, 1.5118839e-03, 2.7946773e-01, 5.8892325e-02,
        6.8766945e-05],
       [9.9361278e-02, 1.3281901e-02, 1.0278437e+00, 5.1964637e-02,
        9.1255558e-01],
       [6.1886859e-01, 1.2031138e+00, 7.2672451e-01, 2.1701832e+00,
        9.4027687e-03]], dtype=float32)>

##### 4.2) Operator Logaritma

In [50]:
# Gunakan fungsi tf.math.log() untuk melakukan operasi logaritma dari 2 tensor
# Perlu diingat bahwa tensor harus memiliki dtype berupa float, baik float32 maupun float64

tf.math.log(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.5219533 ,         nan, -0.85698426, -1.5776606 ,  0.8475494 ],
       [-0.5298355 , -0.46032825,         nan,         nan, -0.7359332 ],
       [        nan,         nan,         nan, -1.4160223 , -4.7923937 ],
       [        nan,         nan,         nan, -1.478596  ,         nan],
       [        nan,         nan, -0.15960394,         nan,         nan]],
      dtype=float32)>

##### 4.3) Operator Pembagian

In [51]:
# Gunakan fungsi tf.divide() untuk melakukan operasi pembagian dari 2 tensor

tf.divide(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.96680212e-01, -1.16841547e-01,  8.48880261e-02,
         2.94939317e-02,  2.12174565e-01],
       [ 4.52847518e-02,  3.71221453e-02, -1.18806966e-01,
        -5.05998433e-02,  1.65192485e-02],
       [-1.78056154e-02, -1.05089066e-03, -1.28938304e-02,
         5.64366067e-03,  1.76437956e-04],
       [-5.94747625e-03, -1.95334130e-03, -1.66201033e-02,
         3.40235117e-03, -1.34546161e-02],
       [-1.07764658e-02, -1.38843721e-02,  1.02708600e-02,
        -1.65522937e-02, -9.99668846e-04]], dtype=float32)>

##### 4.4) Operator Perkalian

In [52]:
# Gunakan fungsi tf.multiply() untuk melakukan operasi perkalian dari 2 tensor

tf.multiply(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   1.1867208 ,   -1.0515739 ,    2.1222007 ,    1.4452027 ,
          25.673122  ],
       [   7.6531234 ,   10.7283    ,  -42.889313  ,  -26.767319  ,
          13.892688  ],
       [ -17.111197  ,   -1.4386692 ,  -21.67453   ,   10.435128  ,
           0.38975143],
       [ -16.70646   ,   -6.7995806 ,  -61.843403  ,   15.273154  ,
         -67.82472   ],
       [ -57.427788  ,  -86.65237   ,   70.75595   , -131.11072   ,
          -9.405884  ]], dtype=float32)>

##### 4.5) Operator Pengurangan

In [53]:
# Gunakan fungsi tf.subtract() untuk melakukan operasi perkurangan dari 2 tensor

tf.subtract(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -1.4066396,  -3.3505247,  -4.5755596,  -6.7935424,  -8.6660795],
       [-12.411298 , -16.368923 , -21.257332 , -24.163795 , -28.520943 ],
       [-31.551973 , -37.038883 , -41.52865  , -42.757324 , -46.991707 ],
       [-53.315216 , -59.115246 , -62.013824 , -66.77204  , -71.95528  ],
       [-73.78668  , -80.09686  , -82.14752  , -90.47315  , -97.09697  ]],
      dtype=float32)>

##### 4.6) Operator Penambahan

In [54]:
# Gunakan fungsi tf.add() untuk melakukan operasi pertambahan dari 2 tensor

tf.add(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.5933604,  2.6494753,  5.4244404,  7.2064576, 13.3339205],
       [13.588702 , 17.631077 , 16.742668 , 21.836205 , 29.479057 ],
       [30.448027 , 36.961117 , 40.47135  , 43.242676 , 47.008293 ],
       [52.684784 , 58.884754 , 59.986176 , 67.22796  , 70.04472  ],
       [72.21332  , 77.90314  , 83.85248  , 87.52685  , 96.90303  ]],
      dtype=float32)>

#### 5) Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [55]:
# Untuk menampilkan nilai maksimal dan minimal dari variabel random_tensor
# gunakan fungsi tf.argmax() dan tf.argmin()

print('Nilai maksimum dari Tensor random_tensor berdasarkan kolom:')
for x, y in enumerate(tf.argmax(random_tensor, axis=0)):
    print('Nilai Kolom-%d Baris-%d: %f' % (x + 1, y, random_tensor[x, y].numpy()))

print('\nNilai maksimum dari Tensor random_tensor berdasarkan baris:')
for x, y in enumerate(tf.argmax(random_tensor, axis=1)):
    print('Nilai Baris-%d Kolom-%d: %f' % (x + 1, y, random_tensor[x, y].numpy()))
    
print('\nNilai minimum dari Tensor random_tensor berdasarkan kolom:')
for x, y in enumerate(tf.argmin(random_tensor, axis=0)):
    print('Nilai Kolom-%d Baris-%d: %f' % (x + 1, y, random_tensor[x, y].numpy()))
    
print('\nNilai minimum dari Tensor random_tensor berdasarkan baris:')
for x, y in enumerate(tf.argmin(random_tensor, axis=1)):
    print('Nilai Baris-%d Kolom-%d: %f' % (x + 1, y, random_tensor[x, y].numpy()))

Nilai maksimum dari Tensor random_tensor berdasarkan kolom:
Nilai Kolom-1 Baris-0: 0.593360
Nilai Kolom-2 Baris-1: 0.631076
Nilai Kolom-3 Baris-4: 0.008293
Nilai Kolom-4 Baris-2: -1.013826
Nilai Kolom-5 Baris-0: -0.786682

Nilai maksimum dari Tensor random_tensor berdasarkan baris:
Nilai Baris-1 Kolom-4: 2.333920
Nilai Baris-2 Kolom-1: 0.631076
Nilai Baris-3 Kolom-3: 0.242677
Nilai Baris-4 Kolom-3: 0.227958
Nilai Baris-5 Kolom-2: 0.852481

Nilai minimum dari Tensor random_tensor berdasarkan kolom:
Nilai Kolom-1 Baris-4: 2.333920
Nilai Kolom-2 Baris-4: 0.479058
Nilai Kolom-3 Baris-1: -0.038883
Nilai Kolom-4 Baris-4: -0.955278
Nilai Kolom-5 Baris-3: -1.473154

Nilai minimum dari Tensor random_tensor berdasarkan baris:
Nilai Baris-1 Kolom-1: -0.350525
Nilai Baris-2 Kolom-2: -2.257332
Nilai Baris-3 Kolom-0: -0.551974
Nilai Baris-4 Kolom-2: -1.013826
Nilai Baris-5 Kolom-3: -1.473154


#### 6) Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [56]:
# Untuk menggabungkan 2 tensor, gunakan fungsi tf.concat()

tf.concat([random_tensor, prime_tensor], axis=0)

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[ 5.9336042e-01, -3.5052463e-01,  4.2444015e-01,  2.0645753e-01,
         2.3339202e+00],
       [ 5.8870178e-01,  6.3107646e-01, -2.2573323e+00, -1.1637964e+00,
         4.7905821e-01],
       [-5.5197406e-01, -3.8882952e-02, -5.2864707e-01,  2.4267741e-01,
         8.2925837e-03],
       [-3.1521624e-01, -1.1524713e-01, -1.0138263e+00,  2.2795753e-01,
        -9.5527774e-01],
       [-7.8668201e-01, -1.0968654e+00,  8.5248137e-01, -1.4731542e+00,
        -9.6967876e-02],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
      

#### 7) Tampilkan hasil sorting dari kedua variable di atas. (descending)

##### 7.1) Tensor random_tensor

In [57]:
# Untuk melakukan proses sortir secara descending, gunakan fungsi tf.sort() dengan parameter direction='DESCENDING'

print('Tensor random_tensor setelah disortir secara descending:')
tf.sort(random_tensor.numpy(), direction='DESCENDING')

Tensor random_tensor setelah disortir secara descending:


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.3339202 ,  0.5933604 ,  0.42444015,  0.20645753, -0.35052463],
       [ 0.63107646,  0.5887018 ,  0.4790582 , -1.1637964 , -2.2573323 ],
       [ 0.2426774 ,  0.00829258, -0.03888295, -0.52864707, -0.55197406],
       [ 0.22795753, -0.11524713, -0.31521624, -0.95527774, -1.0138263 ],
       [ 0.85248137, -0.09696788, -0.786682  , -1.0968654 , -1.4731542 ]],
      dtype=float32)>

##### 7.2) Tensor prime_tensor

In [58]:
# Untuk melakukan proses sortir secara descending, gunakan fungsi tf.sort() dengan parameter direction='DESCENDING'

print('Tensor prime_tensor setelah disortir secara descending:')
tf.sort(prime_tensor.numpy(), direction='DESCENDING')

Tensor prime_tensor setelah disortir secara descending:


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)>