# POSTTEST 7 - Modul Pengenalan TensorFlow
#### Nama : Jorghi Inzaghi Tanson
#### NIM    : 2009106069

##### Import library yang dibutuhkan

In [43]:
import tensorflow as tf

#### 1) Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor dan tampilkan isinya

In [44]:
# Deklarasi variabel random_tensor untuk membuat tensor yang berisi nilai random gunakan fungsi tf.random.normal()

random_tensor = tf.random.normal([5, 5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.2561487 ,  0.29687878,  0.65087503,  1.7259694 ,  1.6681558 ],
       [-0.31113186, -1.612716  , -1.0075768 , -0.4171152 ,  1.813826  ],
       [-0.6462316 , -2.015338  , -1.9451894 ,  1.4860994 , -1.055269  ],
       [-0.17533472,  2.0826657 ,  0.8370288 , -0.25849134, -2.2093742 ],
       [ 0.21309677,  1.5003546 ,  1.8912373 , -0.38746604,  0.6478526 ]],
      dtype=float32)>

#### 2) Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor dan tampilkan isinya

In [45]:
# Deklarasi variabel yang merupakan array yang berisi nilai prima
# Di sini saya memberi batasan berupa nilai prima di bawah 100

arrayPrima = [[2, 3, 5, 7, 11],
              [13, 17, 19, 23, 29],
              [31, 37, 41, 43, 47],
              [53, 59, 61, 67, 71],
              [73, 79, 83, 89, 97]]

# Buat variabel prime_tensor yang menampung fungsi tf.convert_to_tensor

prime_tensor = tf.convert_to_tensor(arrayPrima, dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

#### 3) Tampilkan dimensi dari kedua variable tersebut

In [46]:
# Untuk menampilkan dimensi dari 2 variabel di atas
# gunakan fungsi shape dan get_shape()

print(f'Dimensi dari variabel random_tensor: {random_tensor.shape}',
     f'Dimensi dari variabel prime_tensor: {prime_tensor.get_shape()}',
     sep='\n')

Dimensi dari variabel random_tensor: (5, 5)
Dimensi dari variabel prime_tensor: (5, 5)


#### 4) Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

##### 4.1) Operator Pangkat

In [47]:
# Gunakan fungsi tf.square() atau tf.pow() untuk melakukan operasi perpangkatan dari 2 tensor

tf.square(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1.5779096 , 0.08813702, 0.4236383 , 2.9789705 , 2.7827437 ],
       [0.09680304, 2.6008527 , 1.0152111 , 0.1739851 , 3.2899647 ],
       [0.41761526, 4.061587  , 3.7837617 , 2.2084913 , 1.1135926 ],
       [0.03074227, 4.3374963 , 0.7006172 , 0.06681777, 4.8813343 ],
       [0.04541023, 2.251064  , 3.5767784 , 0.15012993, 0.419713  ]],
      dtype=float32)>

##### 4.2) Operator Logaritma

In [48]:
# Gunakan fungsi tf.math.log() untuk melakukan operasi logaritma dari 2 tensor
# Perlu diingat bahwa tensor harus memiliki dtype berupa float, baik float32 maupun float64

tf.math.log(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[        nan, -1.2144314 , -0.42943764,  0.5457889 ,  0.5117187 ],
       [        nan,         nan,         nan,         nan,  0.5954384 ],
       [        nan,         nan,         nan,  0.39615482,         nan],
       [        nan,  0.73364866, -0.1778968 ,         nan,         nan],
       [-1.546009  ,  0.40570155,  0.63723123,         nan, -0.43409207]],
      dtype=float32)>

##### 4.3) Operator Pembagian

In [49]:
# Gunakan fungsi tf.divide() untuk melakukan operasi pembagian dari 2 tensor

tf.divide(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.62807435,  0.09895959,  0.13017501,  0.24656706,  0.15165053],
       [-0.02393322, -0.09486564, -0.05303036, -0.01813544,  0.06254572],
       [-0.02084618, -0.05446859, -0.04744364,  0.03456045, -0.02245253],
       [-0.0033082 ,  0.03529942,  0.01372178, -0.00385808, -0.03111795],
       [ 0.00291913,  0.01899183,  0.02278599, -0.00435355,  0.00667889]],
      dtype=float32)>

##### 4.4) Operator Perkalian

In [50]:
# Gunakan fungsi tf.multiply() untuk melakukan operasi perkalian dari 2 tensor

tf.multiply(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  -2.5122974,    0.8906363,    3.2543752,   12.081786 ,
          18.349714 ],
       [  -4.0447145,  -27.416172 ,  -19.143959 ,   -9.59365  ,
          52.600952 ],
       [ -20.03318  ,  -74.567505 ,  -79.75276  ,   63.90227  ,
         -49.597645 ],
       [  -9.29274  ,  122.87727  ,   51.058758 ,  -17.31892  ,
        -156.86557  ],
       [  15.556064 ,  118.528015 ,  156.97269  ,  -34.484478 ,
          62.8417   ]], dtype=float32)>

##### 4.5) Operator Pengurangan

In [51]:
# Gunakan fungsi tf.subtract() untuk melakukan operasi perkurangan dari 2 tensor

tf.subtract(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -3.2561488,  -2.7031212,  -4.349125 ,  -5.2740307,  -9.331844 ],
       [-13.3111315, -18.612717 , -20.007576 , -23.417114 , -27.186174 ],
       [-31.64623  , -39.01534  , -42.94519  , -41.5139   , -48.055267 ],
       [-53.175335 , -56.917336 , -60.16297  , -67.25849  , -73.20937  ],
       [-72.7869   , -77.49965  , -81.108765 , -89.38747  , -96.35215  ]],
      dtype=float32)>

##### 4.6) Operator Penambahan

In [52]:
# Gunakan fungsi tf.add() untuk melakukan operasi pertambahan dari 2 tensor

tf.add(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.7438513,  3.2968788,  5.650875 ,  8.725969 , 12.668156 ],
       [12.6888685, 15.387284 , 17.992424 , 22.582886 , 30.813826 ],
       [30.35377  , 34.98466  , 39.05481  , 44.4861   , 45.944733 ],
       [52.824665 , 61.082664 , 61.83703  , 66.74151  , 68.79063  ],
       [73.2131   , 80.50035  , 84.891235 , 88.61253  , 97.64785  ]],
      dtype=float32)>

#### 5) Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [53]:
# Untuk menampilkan nilai maksimal dan minimal dari variabel random_tensor
# gunakan fungsi tf.argmax() dan tf.argmin()

print('Nilai maksimum dari Tensor random_tensor berdasarkan kolom:')
for x, y in enumerate(tf.argmax(random_tensor, axis=0)):
    print('Nilai Kolom-%d: %f \tBaris: %d' % (x + 1, random_tensor[x, y].numpy(), y))

print('\nNilai maksimum dari Tensor random_tensor berdasarkan baris:')
for x, y in enumerate(tf.argmax(random_tensor, axis=1)):
    print('Nilai Baris-%d: %f \tKolom: %d' % (x + 1, random_tensor[x, y].numpy(), y))
    
print('\nNilai minimum dari Tensor random_tensor berdasarkan kolom:')
for x, y in enumerate(tf.argmin(random_tensor, axis=0)):
    print('Nilai Kolom-%d: %f \tBaris: %d' % (x + 1, random_tensor[x, y].numpy(), y))
    
print('\nNilai minimum dari Tensor random_tensor berdasarkan baris:')
for x, y in enumerate(tf.argmin(random_tensor, axis=1)):
    print('Nilai Baris-%d: %f \tKolom: %d' % (x + 1, random_tensor[x, y].numpy(), y))

Nilai maksimum dari Tensor random_tensor berdasarkan kolom:
Nilai Kolom-1: 1.668156 	Baris: 4
Nilai Kolom-2: -0.417115 	Baris: 3
Nilai Kolom-3: -1.055269 	Baris: 4
Nilai Kolom-4: -0.175335 	Baris: 0
Nilai Kolom-5: 1.500355 	Baris: 1

Nilai maksimum dari Tensor random_tensor berdasarkan baris:
Nilai Baris-1: 1.725969 	Kolom: 3
Nilai Baris-2: 1.813826 	Kolom: 4
Nilai Baris-3: 1.486099 	Kolom: 3
Nilai Baris-4: 2.082666 	Kolom: 1
Nilai Baris-5: 1.891237 	Kolom: 2

Nilai minimum dari Tensor random_tensor berdasarkan kolom:
Nilai Kolom-1: -1.256149 	Baris: 0
Nilai Kolom-2: -1.007577 	Baris: 2
Nilai Kolom-3: -1.945189 	Baris: 2
Nilai Kolom-4: 2.082666 	Baris: 1
Nilai Kolom-5: -0.387466 	Baris: 3

Nilai minimum dari Tensor random_tensor berdasarkan baris:
Nilai Baris-1: -1.256149 	Kolom: 0
Nilai Baris-2: -1.612716 	Kolom: 1
Nilai Baris-3: -2.015338 	Kolom: 1
Nilai Baris-4: -2.209374 	Kolom: 4
Nilai Baris-5: -0.387466 	Kolom: 3


#### 6) Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [54]:
# Untuk menggabungkan 2 tensor, gunakan fungsi tf.concat()

tf.concat([random_tensor, prime_tensor], axis=0)

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-1.2561487 ,  0.29687878,  0.65087503,  1.7259694 ,  1.6681558 ],
       [-0.31113186, -1.612716  , -1.0075768 , -0.4171152 ,  1.813826  ],
       [-0.6462316 , -2.015338  , -1.9451894 ,  1.4860994 , -1.055269  ],
       [-0.17533472,  2.0826657 ,  0.8370288 , -0.25849134, -2.2093742 ],
       [ 0.21309677,  1.5003546 ,  1.8912373 , -0.38746604,  0.6478526 ],
       [ 2.        ,  3.        ,  5.        ,  7.        , 11.        ],
       [13.        , 17.        , 19.        , 23.        , 29.        ],
       [31.        , 37.        , 41.        , 43.        , 47.        ],
       [53.        , 59.        , 61.        , 67.        , 71.        ],
       [73.        , 79.        , 83.        , 89.        , 97.        ]],
      dtype=float32)>

#### 7) Tampilkan hasil sorting dari kedua variable di atas. (descending)

##### 7.1) Tensor random_tensor

In [55]:
# Untuk melakukan proses sortir secara descending, gunakan fungsi tf.sort() dengan parameter direction='DESCENDING'

print('Tensor random_tensor setelah disortir secara descending:')
tf.sort(random_tensor.numpy(), direction='DESCENDING')

Tensor random_tensor setelah disortir secara descending:


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.7259694 ,  1.6681558 ,  0.65087503,  0.29687878, -1.2561487 ],
       [ 1.813826  , -0.31113186, -0.4171152 , -1.0075768 , -1.612716  ],
       [ 1.4860994 , -0.6462316 , -1.055269  , -1.9451894 , -2.015338  ],
       [ 2.0826657 ,  0.8370288 , -0.17533472, -0.25849134, -2.2093742 ],
       [ 1.8912373 ,  1.5003546 ,  0.6478526 ,  0.21309677, -0.38746604]],
      dtype=float32)>

##### 7.2) Tensor prime_tensor

In [56]:
# Untuk melakukan proses sortir secara descending, gunakan fungsi tf.sort() dengan parameter direction='DESCENDING'

print('Tensor prime_tensor setelah disortir secara descending:')
tf.sort(prime_tensor.numpy(), direction='DESCENDING')

Tensor prime_tensor setelah disortir secara descending:


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)>