# POSTTEST 7 - Modul Pengenalan TensorFlow
#### Nama : Jorghi Inzaghi Tanson
#### NIM    : 2009106069

##### Import library yang dibutuhkan

In [166]:
import tensorflow as tf

#### 1) Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor dan tampilkan isinya

In [167]:
# Deklarasi variabel random_tensor untuk membuat tensor yang berisi nilai random gunakan fungsi tf.random.normal()

random_tensor = tf.random.normal([5, 5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.3274251 , -0.56492066, -1.1743252 ,  0.2617222 ,  0.5138776 ],
       [-0.6808456 , -1.0943954 , -0.0048005 ,  0.10920021, -0.4473078 ],
       [-0.20212822, -1.0283024 , -1.5350406 , -1.7779982 , -0.00385202],
       [ 1.4321536 , -0.14831477, -0.41424876,  2.0363421 , -0.1329046 ],
       [-0.01684707, -0.32566223,  0.49628872, -0.28865185, -0.5365857 ]],
      dtype=float32)>

#### 2) Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor dan tampilkan isinya

In [168]:
# Deklarasi variabel yang merupakan array yang berisi nilai prima
# Di sini saya memberi batasan berupa nilai prima di bawah 100

arrayPrima = [[2, 3, 5, 7, 11],
              [13, 17, 19, 23, 29],
              [31, 37, 41, 43, 47],
              [53, 59, 61, 67, 71],
              [73, 79, 83, 89, 97]]

# Buat variabel prime_tensor yang menampung fungsi tf.convert_to_tensor

prime_tensor = tf.convert_to_tensor(arrayPrima, dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

#### 3) Tampilkan dimensi dari kedua variable tersebut

In [169]:
# Untuk menampilkan dimensi dari 2 variabel di atas
# gunakan fungsi shape dan get_shape()

print(f'Dimensi dari variabel random_tensor: {random_tensor.shape}',
     f'Dimensi dari variabel prime_tensor: {prime_tensor.get_shape()}',
     sep='\n')

Dimensi dari variabel random_tensor: (5, 5)
Dimensi dari variabel prime_tensor: (5, 5)


#### 4) Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

##### 4.1) Operator Pangkat

In [170]:
# Gunakan fungsi tf.square() atau tf.pow() untuk melakukan operasi perpangkatan dari 2 tensor

tf.square(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1.07207194e-01, 3.19135368e-01, 1.37903976e+00, 6.84985146e-02,
        2.64070153e-01],
       [4.63550746e-01, 1.19770133e+00, 2.30448077e-05, 1.19246859e-02,
        2.00084269e-01],
       [4.08558175e-02, 1.05740595e+00, 2.35634971e+00, 3.16127753e+00,
        1.48380632e-05],
       [2.05106378e+00, 2.19972730e-02, 1.71602041e-01, 4.14668941e+00,
        1.76636335e-02],
       [2.83823785e-04, 1.06055886e-01, 2.46302485e-01, 8.33198950e-02,
        2.87924200e-01]], dtype=float32)>

##### 4.2) Operator Logaritma

In [171]:
# Gunakan fungsi tf.math.log() untuk melakukan operasi logaritma dari 2 tensor
# Perlu diingat bahwa tensor harus memiliki dtype berupa float, baik float32 maupun float64

tf.math.log(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[        nan,         nan,         nan, -1.3404716 , -0.66577023],
       [        nan,         nan,         nan, -2.2145722 ,         nan],
       [        nan,         nan,         nan,         nan,         nan],
       [ 0.35917932,         nan,         nan,  0.7111551 ,         nan],
       [        nan,         nan, -0.7005974 ,         nan,         nan]],
      dtype=float32)>

##### 4.3) Operator Pembagian

In [172]:
# Gunakan fungsi tf.divide() untuk melakukan operasi pembagian dari 2 tensor

tf.divide(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.6371255e-01, -1.8830688e-01, -2.3486504e-01,  3.7388887e-02,
         4.6716142e-02],
       [-5.2372739e-02, -6.4376198e-02, -2.5265795e-04,  4.7478350e-03,
        -1.5424407e-02],
       [-6.5202652e-03, -2.7791958e-02, -3.7440017e-02, -4.1348796e-02,
        -8.1957885e-05],
       [ 2.7021766e-02, -2.5138098e-03, -6.7909635e-03,  3.0393166e-02,
        -1.8718959e-03],
       [-2.3078179e-04, -4.1223066e-03,  5.9793820e-03, -3.2432792e-03,
        -5.5318112e-03]], dtype=float32)>

##### 4.4) Operator Perkalian

In [173]:
# Gunakan fungsi tf.multiply() untuk melakukan operasi perkalian dari 2 tensor

tf.multiply(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-6.5485018e-01, -1.6947620e+00, -5.8716259e+00,  1.8320554e+00,
         5.6526532e+00],
       [-8.8509932e+00, -1.8604721e+01, -9.1209516e-02,  2.5116048e+00,
        -1.2971926e+01],
       [-6.2659745e+00, -3.8047192e+01, -6.2936665e+01, -7.6453926e+01,
        -1.8104498e-01],
       [ 7.5904137e+01, -8.7505713e+00, -2.5269175e+01,  1.3643492e+02,
        -9.4362268e+00],
       [-1.2298361e+00, -2.5727316e+01,  4.1191963e+01, -2.5690016e+01,
        -5.2048813e+01]], dtype=float32)>

##### 4.5) Operator Pengurangan

In [174]:
# Gunakan fungsi tf.subtract() untuk melakukan operasi perkurangan dari 2 tensor

tf.subtract(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -2.327425 ,  -3.5649207,  -6.174325 ,  -6.738278 , -10.486122 ],
       [-13.680845 , -18.094395 , -19.0048   , -22.8908   , -29.447308 ],
       [-31.202127 , -38.0283   , -42.53504  , -44.778    , -47.003853 ],
       [-51.56785  , -59.148315 , -61.41425  , -64.96366  , -71.132904 ],
       [-73.016846 , -79.32566  , -82.50371  , -89.28865  , -97.53658  ]],
      dtype=float32)>

##### 4.6) Operator Penambahan

In [175]:
# Gunakan fungsi tf.add() untuk melakukan operasi pertambahan dari 2 tensor

tf.add(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.6725749,  2.4350793,  3.8256748,  7.261722 , 11.513878 ],
       [12.319155 , 15.905604 , 18.9952   , 23.1092   , 28.552692 ],
       [30.797873 , 35.9717   , 39.46496  , 41.222    , 46.996147 ],
       [54.43215  , 58.851685 , 60.58575  , 69.03634  , 70.867096 ],
       [72.983154 , 78.67434  , 83.49629  , 88.71135  , 96.46342  ]],
      dtype=float32)>

#### 5) Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [176]:
# Untuk menampilkan nilai maksimal dan minimal dari variabel random_tensor
# gunakan fungsi tf.argmax() dan tf.argmin()

print('Nilai maksimum dari Tensor random_tensor berdasarkan kolom:')
for x, y in enumerate(tf.argmax(random_tensor, axis=0)):
    print('Nilai Ke-%d: %f\t\tKolom: %d' % (x + 1, random_tensor[x, y].numpy(), y))

print('\nNilai maksimum dari Tensor random_tensor berdasarkan baris:')
for x, y in enumerate(tf.argmax(random_tensor, axis=1)):
    print('Nilai Ke-%d: %f\t\tKolom: %d' % (x + 1, random_tensor[x, y].numpy(), y))
    
print('\nNilai minimum dari Tensor random_tensor berdasarkan kolom:')
for x, y in enumerate(tf.argmin(random_tensor, axis=0)):
    print('Nilai Ke-%d: %f\t\tKolom: %d' % (x + 1, random_tensor[x, y].numpy(), y))
    
print('\nNilai minimum dari Tensor random_tensor berdasarkan baris:')
for x, y in enumerate(tf.argmin(random_tensor, axis=1)):
    print('Nilai Ke-%d: %f\t\tKolom: %d' % (x + 1, random_tensor[x, y].numpy(), y))

Nilai maksimum dari Tensor random_tensor berdasarkan kolom:
Nilai Ke-1: 0.261722		Kolom: 3
Nilai Ke-2: 0.109200		Kolom: 3
Nilai Ke-3: -0.003852		Kolom: 4
Nilai Ke-4: 2.036342		Kolom: 3
Nilai Ke-5: -0.016847		Kolom: 0

Nilai maksimum dari Tensor random_tensor berdasarkan baris:
Nilai Ke-1: 0.513878		Kolom: 4
Nilai Ke-2: 0.109200		Kolom: 3
Nilai Ke-3: -0.003852		Kolom: 4
Nilai Ke-4: 2.036342		Kolom: 3
Nilai Ke-5: 0.496289		Kolom: 2

Nilai minimum dari Tensor random_tensor berdasarkan kolom:
Nilai Ke-1: -0.564921		Kolom: 1
Nilai Ke-2: -1.094395		Kolom: 1
Nilai Ke-3: -1.535041		Kolom: 2
Nilai Ke-4: -0.414249		Kolom: 2
Nilai Ke-5: -0.536586		Kolom: 4

Nilai minimum dari Tensor random_tensor berdasarkan baris:
Nilai Ke-1: -1.174325		Kolom: 2
Nilai Ke-2: -1.094395		Kolom: 1
Nilai Ke-3: -1.777998		Kolom: 3
Nilai Ke-4: -0.414249		Kolom: 2
Nilai Ke-5: -0.536586		Kolom: 4


#### 6) Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [177]:
# Untuk menggabungkan 2 tensor, gunakan fungsi tf.concat()

tf.concat([random_tensor, prime_tensor], axis=0)

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-3.2742509e-01, -5.6492066e-01, -1.1743252e+00,  2.6172221e-01,
         5.1387757e-01],
       [-6.8084562e-01, -1.0943954e+00, -4.8005008e-03,  1.0920021e-01,
        -4.4730780e-01],
       [-2.0212822e-01, -1.0283024e+00, -1.5350406e+00, -1.7779982e+00,
        -3.8520207e-03],
       [ 1.4321536e+00, -1.4831477e-01, -4.1424876e-01,  2.0363421e+00,
        -1.3290460e-01],
       [-1.6847070e-02, -3.2566223e-01,  4.9628872e-01, -2.8865185e-01,
        -5.3658569e-01],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
      

#### 7) Tampilkan hasil sorting dari kedua variable di atas. (descending)

##### 7.1) Tensor random_tensor

In [178]:
# Untuk melakukan proses sortir secara descending, gunakan fungsi tf.sort() dengan parameter direction='DESCENDING'

print('Tensor random_tensor setelah disortir secara descending:')
tf.sort(random_tensor.numpy(), direction='DESCENDING')

Tensor random_tensor setelah disortir secara descending:


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.5138776 ,  0.2617222 , -0.3274251 , -0.56492066, -1.1743252 ],
       [ 0.10920021, -0.0048005 , -0.4473078 , -0.6808456 , -1.0943954 ],
       [-0.00385202, -0.20212822, -1.0283024 , -1.5350406 , -1.7779982 ],
       [ 2.0363421 ,  1.4321536 , -0.1329046 , -0.14831477, -0.41424876],
       [ 0.49628872, -0.01684707, -0.28865185, -0.32566223, -0.5365857 ]],
      dtype=float32)>

##### 7.2) Tensor prime_tensor

In [179]:
# Untuk melakukan proses sortir secara descending, gunakan fungsi tf.sort() dengan parameter direction='DESCENDING'

print('Tensor prime_tensor setelah disortir secara descending:')
tf.sort(prime_tensor.numpy(), direction='DESCENDING')

Tensor prime_tensor setelah disortir secara descending:


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)>